AllCops:
  Exclude:
    - "vendor/**/*"

LineLength:
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - "**/metadata.rb"
